### PR TITLE
[px_render_gltf] Add tangent support + fix sampler error

### PR DESCRIPTION
**Pull request by NukeBird**

### CODE REVIEW

**Comment by NukeBird** [comment]
Please note that tangents can be vec4

> XYZW vertex tangents where the w component is a sign value (-1 or +1) indicating handedness of the tangent basis

> Implementation note: When normals and tangents are specified, client implementations should compute the bitangent by taking the cross product of the normal and tangent xyz vectors and multiplying against the w component of the tangent: bitangent = cross(normal, tangent.xyz) * tangent.w

Also tangents can be vec3, so w component can be 0

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#tangent-space-definition

**Comment by pplux** [comment]
Nice! I'll check it out as soon as possible! thanks

**Review by pplux — CHANGES_REQUESTED** [review]
Looks indeed, nice, but there is a tab vs space mismatch, could you give it a try?

**Comment by NukeBird** [comment]
Is it better now?

**Comment by pplux** [comment]
Perfect! just a couple of things, there are empty changes in the px_render.h (only spaces) that are not needed (do checkout from master), and finally you need to flatten your PR into just one commit (rebase -i && push force), that way there is only one commit and gets easier to follow changes, bisect, and so on.

Thanks!

**Comment by NukeBird** [comment]
I'm sorry if I did something wrong, I don't know git too well :(

**Review by pplux — APPROVED** [review]
Good! thanks!

**Pull request merged**
